title: "Nishant Bansal's Corner of the Web"
author:
  name: "Nishant Bansal"
description: "Under construction — stay tuned!"
theme: minima

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/nishantbansal2509
    - platform: linkedin
      user_url: https://linkedin.com/in/nishantbansal2509
